import assert from 'node:assert/strict'
import { stat, unlink } from 'node:fs/promises'
import puppeteer from 'puppeteer-core'

const url = process.env.PLAY_URL ?? 'http://127.0.0.1:3000'
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const page = await browser.newPage()
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
const state = () => page.evaluate(() => window.__badminton__.getState())
const waitState = expression => page.waitForFunction(expression, { timeout: 12000 })
const click = name => page.click(`[data-ui="${name}"]`)
try {
  await page.goto(url, { waitUntil: 'networkidle0' })
  await page.screenshot({ path: '/tmp/badminton-accept-menu.png' })
  await page.select('#play-difficulty', 'medium')
  await page.select('#play-style', 'rally')
  await click('start-training')
  await waitState(() => window.__badminton__.getState().mode === 'training')
  assert.equal((await state()).phase, 'idle')
  assert.equal(await page.evaluate(() => window.__badminton__.isRecording()), false)
  const cdp = await browser.target().createCDPSession()
  await cdp.send('Browser.setDownloadBehavior', { behavior: 'allowAndName', downloadPath: '/tmp', eventsEnabled: true })
  const download = new Promise(resolve => cdp.on('Browser.downloadProgress', event => { if (event.state === 'completed') resolve(event.guid) }))
  await click('record')
  assert.equal(await page.evaluate(() => window.__badminton__.isRecording()), true)
  await page.evaluate(() => new Promise(resolve => {
    let frames = 0
    function frame() { if (++frames === 30) resolve(); else requestAnimationFrame(frame) }
    requestAnimationFrame(frame)
  }))
  await click('record')
  const file = `/tmp/${await download}`
  assert.ok((await stat(file)).size > 1000)
  await unlink(file)
  await page.click('canvas')
  await page.keyboard.down('w')
  await waitState(() => window.__badminton__.getState().players[0].pos[0] > -2.7)
  await page.keyboard.up('w')
  await page.keyboard.press('Escape')
  await waitState(() => window.__badminton__.getState().phase === 'paused')
  const paused = await state()
  await page.keyboard.press('w')
  assert.deepEqual((await state()).players[0].pos, paused.players[0].pos)
  await click('restart')
  await waitState(() => window.__badminton__.getState().phase === 'idle')
  for (const [key, shot] of [['1','CLEAR'], ['2','DROP'], ['3','SMASH'], ['4','DRIVE'], ['5','NET_DROP'], ['6','LIFT']]) {
    await page.keyboard.press(key)
    assert.equal((await state()).players[0].selectedShot, shot)
  }
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowUp')
  assert.deepEqual((await state()).players[0].aim, { lateral: -1, depth: 1 })
  await page.keyboard.press('x')
  await page.keyboard.press('1')
  await page.keyboard.press('Space')
  await waitState(() => window.__badminton__.getState().phase === 'playing')
  await page.screenshot({ path: '/tmp/badminton-accept-play.png' })
  await waitState(() => window.__badminton__.getState().rallyHits >= 1 || !!window.__badminton__.getState().lastPoint)
  await page.evaluate(async () => {
    window.__testPhysics = await import('/src/physics/shuttlecock.ts')
    window.__testTactics = await import('/src/ai/tactical.ts')
  })
  await waitState(() => {
    const s = window.__badminton__.getState()
    if (!s.shuttle || s.lastHitter !== 1) return false
    const future = window.__testPhysics.stepShuttlecock(s.shuttle, 0.12, undefined, 12)
    return future.pos[1] < 2.25 && window.__testTactics.getLegalShots(s.players[0], future).includes('CLEAR')
  })
  await page.keyboard.press('j')
  await waitState(() => window.__badminton__.getState().training.returns >= 1)
  console.log('human return', (await state()).players[0].feedback)
  await waitState(() => window.__badminton__.getState().players[0].swing.phase === 'ready')
  await page.keyboard.press('Space')
  await waitState(() => window.__badminton__.getState().players[0].body.phase === 'airborne' && window.__badminton__.getState().players[0].pos[1] > 0.25)
  const jumping = await state()
  assert.ok(jumping.players[0].pos[1] > 0)
  await page.keyboard.press('l')
  await page.screenshot({ path: '/tmp/badminton-accept-jump.png' })
  await page.keyboard.press('Escape')
  await waitState(() => window.__badminton__.getState().phase === 'paused')
  await click('return-menu')
  await page.select('#play-difficulty', 'easy')
  await page.select('#play-style', 'attacker')
  await page.select('#play-loadout', 'control')
  await click('start-match')
  await waitState(() => window.__badminton__.getState().mode === 'match')
  assert.equal((await state()).players[0].loadout, 'control')
  await page.keyboard.press('Space')
  await page.keyboard.press('q')
  await waitState(() => window.__badminton__.getState().players[0].body.action === 'scissor')
  await page.keyboard.down('ShiftLeft')
  await page.keyboard.press('j')
  await page.keyboard.up('ShiftLeft')
  assert.equal((await state()).players[0].swing.slice, true)
  await waitState(() => !!window.__badminton__.getState().lastPoint)
  const point = await state()
  assert.equal(point.match.points[0] + point.match.points[1], 1)
  await page.keyboard.press('Escape')
  await waitState(() => window.__badminton__.getState().phase === 'paused')
  await page.screenshot({ path: '/tmp/badminton-accept-pause.png' })
  await page.setViewport({ width: 960, height: 640 })
  await click('return-menu')
  await page.evaluate(() => Promise.all(document.getAnimations().filter(animation => animation.effect?.getTiming().iterations !== Infinity).map(animation => animation.finished)))
  await page.screenshot({ path: '/tmp/badminton-accept-960.png' })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  assert.deepEqual(errors, [])
  console.log('Browser checks passed: menu, inputs, manual serve, AI return, score, pause, restart, settings, narrow viewport; no Console/HTTP errors.')
} catch (error) {
  console.log('failed state', JSON.stringify(await state()), await page.evaluate(() => ({ active: document.activeElement?.tagName, focusedControl: document.activeElement?.getAttribute('data-ui'), dialog: document.querySelector('[data-ui="break-dialog"]')?.hidden })))
  await page.screenshot({ path: '/tmp/badminton-accept-failure.png' })
  throw error
} finally {
  await browser.close()
}
